# -*- coding: utf-8 -*-
{ :language => 'français',
  :keywords => "gibier, tradition, autoroute, chambre, dormir, étape",
  :ieBannerTitle => "Vous utilisez un navigateur obsolete",
  :ieBannerText => "Pour une meilleure expérience avec ce site, s'il vous plait migrez vers un navigateur plus moderne.",
  :description => "Site officiel d'information de l'Auberge aux trois marcassins",
  :indexTab => "Accueil",
  :restoTab => "Restaurant",
  :hotelTab => "Hotel",
  :infoTab => "Informations",
  :gallery => "Cliquez pour d'autres photos",

  :tablePic => "Photo d'une table de la salle",
  :indexTitle => "Bienvenue en Lorraine ...",
  :indexContent1 => "Au cœur du pays lorrain, l’Auberge Aux Trois Marcassins vous réserve un accueil chaleureux et convivial.",
  :indexContent2 => "Dans une ambiance discrètement chic, prenez le temps de découvrir ou redécouvrir une cuisine de terroir de qualité...",
  :indexContent3 => "...et reposez-vous dans nos chambres spacieuses et confortables.",
  :freshInfo => "Dernières actualités",

  :restoTitle => "L'authenticité",
  :restoSubTitle1 => "... au service de vos papilles ...",
  :restoContent1 => "Dans une ancienne maison lorraine restaurée, tout en poutres et pierres apparentes, Monsieur et Madame Bourgau vous proposent une cuisine traditionnelle de caractère. ",
  :restoSubTitle2 => "... au rythme des saisons ...",
  :restoContent2 => "Notre Chef, passionné, laisse libre court à son imagination en laissant évoluer les plats proposés au fil des saisons, avec les produits du marché. Le gibier, en période autorisée, est invité à la carte.",
  :restoContent3 => "Ancien sommelier d'un Restaurant Londonnien étoilé, notre chef saura vous guider dans vos choix de vins de qualité",
  :restoContent4 => "Tout est ici Authentique, y compris les desserts, réalisés par l'épouse de notre Chef.",
  :restoPrices => "Carte & tarifs",

  :hotelTitle => "Reposez-vous",
  :hotelContent1 => "L'Auberge Aux Trois Marcassins vous propose également ses chambres confortables et spacieuses, décorées avec soin.",
  :hotelContent2 => "Nous pouvons accueillir de une à quatre personnes dans nos chambres toutes équipées de salle de bain/douche et wc, téléphone, télévision, et accès wifi libre.",
  :hotelContent3 => "Pourquoi ne pas opter pour une Soirée Etape (formule intégrale comprenant le diner, la nuit et le petit déjeuner) pour une ou deux personnes à un tarif avantageux?",
  :hotelPrices => "Formules & Tarifs",
  :hotelBooking => "Réserver une chambre",
  :hotelBookingTitle => "Réserver une chambre en ligne sur reservit",
  :hotelBookingUrl => "http://hotel.reservit.com/reservit/reserhotel.php?lang=FR&hotelid=6297",

  :infoTitle => "Comment nous rejoindre?",
  :howToCome => "Située entre Metz et Nancy, à une minute de l'Axe autoroutier A31, sortie 25, L'Auberge Aux Trois Marcassins vous attend",
  :mapTitle => "Situer l'auberge sur Google Maps",
  :emailTitle => "Contacter l'auberge par email",
  :weeklyClosureTitle => "Fermeture hebdomadaire",
  :weeklyClosure => "Samedi et lundi midis, Dimanche midi et soir",
  :yearlyClosureTitle => "Fermeture annuelle",
  :yearlyClosure1 => "Une semaine à partir du 26 décembre",
  :yearlyClosure2 => "Deux semaines en avril",
  :freshInfoTitle => "Actualités régulièrement mises à jour",

  :captionFrontDoor => "Porte d'entrée",
  :captionFrontLeft => "Facade vue de gauche",
  :captionFrontRight => "Facade vue de droite",
  :captionHotelRoom1 => "Chambre n°1",
  :captionHotelRoom21 => "Chambre n°2",
  :captionHotelRoom22 => "Chambre n°2",
  :captionHotelRoom23 => "Chambre n°2",
  :captionHotelRoom4 => "Chambre n°4",
  :captionRestoBirdJelly => "Effilochade de laperau",
  :captionRestoBoar => "Vue détaillée de la salle",
  :captionRestoCheese => "Plateau de fromages",
  :captionRestoCustomers => "Clients prenant leur déjeuner",
  :captionRestoDeer => "Cerf grillé",
  :captionRestoFatLiver => "Foie gras cuit",
  :captionRestoHearth => "Cheminée dans la salle",
  :captionRestoMainRoom => "Salle à manger principale",
  :captionRestoSmallRoom => "Seconde salle en caveau",
  :captionRestoSmallRoomTable => "Table dressée dans le caveau",
  :captionRestoTable => "Table dressée"
}
